#!/usr/bin/env ruby

src = '/Volumes/Foo/DICOM/S00001/*/*'
dst = '/some/path'

require 'fileutils'

Dir.glob(src).each do |path|
  name = File.basename(path)
  dir = File.dirname(path).split('/').last
  FileUtils.mkdir_p("#{dst}/#{dir}")
  cmd = p("convert #{path} #{dst}/#{dir}/#{name}.png")
  system cmd
end
